# Advanced configuration file for DustBin plugin
# Some of these settings are safe, others can break your server if modified incorrectly
# New settings/defaults won't appear automatically on this file when upgrading

settings:
  #Multi-language setting
  #Available: eng, kor
  language: "eng"

  update-check: false


command:
  #Name of main command
  #You can change this to be what you want
  name: "dustbin"

  #Aliases of main command
  #You can add, replace, or remove them as you like
  aliases: ["db", "trash"]


permission:
  #Permission of main command
  #You can change this to be what you want
  main: "true"